import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, ClerkLoaded, ClerkLoading } from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { merriweather } from '@/app/ui/fonts';
import localFont from 'next/font/local';
import Loader from '@/components/Loader';

export const segoeUI = localFont({
  src: './fonts/segoeui.ttf',
  variable: '--font-segoe-ui',
});
export const sourceSerif = localFont({
  src: './fonts/source-serif-pro.ttf',
  variable: '--font-source-serif-pro',
});
export const sohne = localFont({
  src: './fonts/sohne.otf',
  variable: '--font-sohne',
});

export const segoeui1 = localFont({
  src: './fonts/segeoui1.ttf',
  variable: '--font-segoe-ui-regular'
});



const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${inter.className} ${merriweather.className} ${sohne.className} ${sourceSerif.className}  ${segoeui1.className}`}>
          <ClerkLoading>
            <div className="flex items-center justify-center h-screen text-2xl">
              <Loader/>
            </div>
          </ClerkLoading>
          <ClerkLoaded>
            <div className="max-w-7xl mx-auto">
              <div className="flex flex-col h-screen">
                <Navbar />
                {children}
              </div>
            </div>
          </ClerkLoaded>
        </body>
      </html>
    </ClerkProvider>
  );
}
